#include <iostream>
#include <vector>
using namespace std;
// Pre-declare function
class Product;

class Box{
private:
    double volume;
public:
    void setVolume(double);
    bool checkSize(Box,Product);
};

class Product{
private:
    double length;
    double width;
    double depth;
public:
    void setDimensions(double,double,double);
    friend bool Box::checkSize(Box,Product);
};

void Box::setVolume(double vol) {
    this->volume = vol;
}

bool Box::checkSize(Box b, Product p) {
    if (p.length * p.width * p.depth > b.volume ){
        return false;
    } else if (p.length * p.width * p.depth < b.volume){
        return true;
    } else {
        return false;
    }
}

void Product::setDimensions(double len, double wid, double dep) {
    this->length = len;
    this->width = wid;
    this->depth = dep;

}

int main() {
    int volume;
    string lwd, depth, width, length;
    double p1,p2,p3;
    bool le = false, we = false, de = false;

    Product product1;
    Box box1;
    cout << "Enter box volume: ";
    cin >> volume;
    cout << "Enter product length, width and depth: ";
    cin.ignore(); //Need to flush the \n generated by first cin.
    getline(cin, lwd);
    for(char i : lwd){
        if (i == ' ' && !le){
            le = true;
            continue;
        } else if (i == ' ' && !we){
            we = true;
            continue;
        } else if (i == ' ' && !de){
            de = true;
            continue;
        } else {
            if (!le){
                length += i;
            } else if (!we){
                width += i;
            } else if (!de){
                depth += i;
            }
        }
    }
    p1 = atof(length.c_str());
    p2 = atof(width.c_str());
    p3 = atof(depth.c_str());
    box1.setVolume(volume);
    product1.setDimensions(p1,p2,p3);
    cout << "Does the product fit in the box? (1 - yes, 0 - no): " << box1.checkSize(box1,product1);
}
